version: '3'

services:
  app1:
    image: melissapanduro/chatbot_docker
    ports:
      - "8085:8085"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY}
  app2:
    image: melissapanduro/front_docker
    container_name: frontend
    ports:
      - "4200:4200"



